site_name: Parth Patel's Website

theme:
    name: 'material'
    font: 
      text: JetBrains Mono
      code: 
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: light
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        extra_css:
          - stylesheets/extra.css

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: dark
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        extra_css:
          - stylesheets/extra.css

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
